XKNX/knx-frontend

build-scripts/webpack.js, package.json, src/entrypoint.ts, src/knx-router.ts, src/knx.ts, src/knx_ui.ts, src/main.ts, src/services/websocket.service.ts, src/types/knx.ts, src/views/bus_monitor.ts, src/views/overview.ts, tsconfig.json, yarn.lock
Use `@ha` instead of relative imports for homeassistant-frontend components.
For webpack to work with that https://github.com/dividab/tsconfig-paths-webpack-plugin is added.
I think its better readable and it will also pave the way for `eslint` to pass.
=> feat: Scoped path for homeassistant frontend

.github/workflows/build.yml, .github/workflows/ci.yml, src/knx-router.ts, src/knx.ts, src/main.ts, src/views/bus_monitor.ts, src/views/overview.ts
- Removed some unused imports.
- use `nothing` when returning empty template.
- use !== instead of !=
- Sort imports, add empty line between lit, ha and knx imports.
=> chore: lint, sort, format, repeat

src/services/websocket.service.ts, src/types/websocket.ts, src/views/group_monitor.ts
The integration counterpart is found here: [Send recent telegrams at once on connection of group monitor](https://github.com/home-assistant/core/pull/93153/commits/20f9b8f17dcb9eddb236f2c2b87ef092bc90adf3)
in https://github.com/home-assistant/core/pull/93153
=> Prepopulate group monitor table with recent telegrams

script/upgrade-frontend
Since `/homeassistant-frontend/node_modules` is used, but not updated when checking out a new branch (as it is listed in `.gitignore`) it would stay on older versions.
=> Add `yarn install` to upstream when updating HA-frontend

package.json, script/merge_requirements.js, script/upgrade-frontend, yarn.lock
and apply for 20230601.1
- run `yarn dedupe` when moving to a new tag
- fix resolutions paths instead of having to use manual `resolutionOverride` for each
- add packageManager key
=> Update scripts for HA-FE updates

src/dialogs/knx-telegram-info-dialog.ts, src/localize/languages/de.json, src/localize/languages/en.json, src/services/websocket.service.ts, src/types/websocket.ts, src/utils/format.ts, src/views/group_monitor.ts
adds DPT information to the Group monitors info dialog
This needs the websocket methods updated in the backend. https://github.com/home-assistant/core/commit/7c0e88d946767c6cdbf15b288a4c2b9edb87c252
=> Use `TelegramDict` object from backend, add DPT infos

src/__init__.py
These are marked `Final` now and don't need to be called (`entrypoint_js` instead of `entrypoint_js()`) which looks cleaner and is less error prone.
Also added `webcomponent_name` as this should live in the panel package instead of the integration.
closes #77 
example use:
```py
import knx_frontend as knx_panel
if DOMAIN not in hass.data.get("frontend_panels", {}):
hass.http.register_static_path(
URL_BASE,
path=knx_panel.locate_dir(),
cache_headers=knx_panel.is_prod_build,
)
await panel_custom.async_register_panel(
hass=hass,
frontend_url_path=DOMAIN,
webcomponent_name=knx_panel.webcomponent_name,
sidebar_title=DOMAIN.upper(),
sidebar_icon="mdi:bus-electric",
module_url=f"{URL_BASE}/{knx_panel.entrypoint_js}",
embed_iframe=True,
require_admin=True,
)
=> Use module variables in `__init__.py` for static values

src/views/group_monitor.ts
Currently in German (and possibly also other long languages) the text for the telegram direction gets cut off and there is more than enough space around it to make the column wider.
Only downside is on mobile, but for that use case the table should anyway be enhanced to then display rows that use two lines (as the HA frontend in general does).
=> Increase column width for telegram direction

src/dialogs/knx-telegram-info-dialog.ts
eg. GroupValueRead has no value and payload - so we don't need to render these rows. Same for telegrams we have no value for, but only a payload.
=> GM Info dialog: Hide value and payload when null

pyproject.toml
Since setuptools is already on version 68.1.2.
=> Relax setuptools build dependency

src/main.ts
to have proper back arrow directions 🔙
=> Inherit reading direction style from hass

src/views/entities_create.ts
This should hide the device tree for most mobile phones in portrait orientation, but still show it in landscape orientation.
related: https://github.com/home-assistant/core/issues/123262
=> Hide entity-editor device-tree on narrow screens

src/components/knx-project-device-tree.ts
... which is quite unlikely, but may occur on test projects or something like that, so better to show something, rather than a blank panel.
=> Show info when no suitable group object found in project data

src/knx-router.ts, src/knx.ts, src/main.ts, src/types/knx.ts, src/views/info.ts
- Show project tab only when project is available
- reload KNX object when project is uploaded or deleted
- store KNXInfoData in KNX object to be available globally - and not load it in info tab
closes #156
=> Hide "Project" tab when user has not uploaded an ETS project

src/components/knx-configure-entity-options.ts, src/components/knx-configure-entity.ts, src/utils/schema.ts
These default to `expanded` when a group address is defined (edit mode) in any child-field. Otherwise they default `collapsed`.
=> Collapsible sections in entity configuration 

src/main.ts
=> Forward "a", "d" and "m" keyboard shortcuts

src/components/knx-configure-entity.ts, src/components/knx-sync-state-selector-row.ts, src/utils/schema.ts
in favour of a plain group with a `heading`.
Add description to `knx-sync-state-selector-row`
=> Remove `advanced` option for `settings_group`

src/utils/schema.ts
Linked to Issue #210. Removes the upper limit for reset_after parameter.
This converts the slider into a number input box only.
=> Extend reset after limit

src/localize/languages/de.json, src/localize/languages/en.json, src/views/entities_view.ts, src/views/group_monitor.ts, src/views/project_view.ts
This update enhances the Group Monitor by enabling URL-based filtering of telegrams. It also introduces contextual quick links from the project and entity views that open the Group Monitor with pre-applied filters — making it easier to inspect only the relevant telegrams for a given group address or entity. You can now share or bookmark filtered views to easily preserve and revisit complex filter settings.
=> Extend Group Monitor with URL filtering

src/components/data-table/filter/knx-list-filter.ts, src/components/knx-separator.ts, src/components/knx-sort-menu.ts, src/localize/languages/de.json, src/localize/languages/en.json
This PR enhances the usability of the `knx-list-filter` by adding a **_Scroll-to-Selection_** button. When `pinSelectedItems` is enabled and the current selection is outside the visible viewport, a button appears to guide the user back to the selection area.
=> Improve knx-list-filter usability with scroll-to-selection button

src/components/data-table/filter/knx-list-filter.ts, src/components/knx-sort-menu-item.ts, src/features/group-monitor/views/group-monitor-view.ts
This PR ensures that only sorting options relevant to the current context are displayed in the filters. The Sort by Filter Count option is now only shown when filter options are currently selected or when this sorting option is already active.
=> Show only selectable sorting options in filters

src/components/data-table/filter/knx-list-filter.ts, src/features/group-monitor/views/group-monitor-view.ts
This PR makes a small layout optimization and a bug fix:
- Reduced the spacing between the name and description in the list filters for a cleaner look.
- Fixed a visual glitch occurred when switching between the Group Monitor and other menu entries
https://github.com/user-attachments/assets/1867a539-a2ad-4eb5-9f26-8102927e906d
=> Improve Group Monitor layout spacing and navbar behavior

src/components/data-table/filter/knx-list-filter.ts, src/components/knx-sort-menu-item.ts, src/features/group-monitor/controller/group-monitor-controller.ts, src/features/group-monitor/views/group-monitor-view.ts, src/localize/languages/de.json, src/localize/languages/en.json
**New Feature:**
- When opening the group monitor without an ETS project loaded, a banner is now displayed, informing the user that more details are available after uploading the ETS file.
**Bugfixes:**
- Fixed offset formatting issue when no field was sorted (natural sorting).
- Fixed display bug in the sort menu where sorting entries were hidden with delay, even though they were already inactive.
- Cached FilterPanel config to reduce redundant renders.
- Minor CSS improvements.
=> Add banner in group monitor when no ETS project is loaded + various bugfixes

src/components/knx-group-address-selector.ts, src/knx-router.ts, src/knx.ts, src/services/websocket.service.ts, src/types/knx.ts, src/types/websocket.ts, src/views/entities_create.ts, src/views/info.ts, src/views/project_view.ts
So we can just check `this.knx.projectInfo?` for a project being available 
and `this.knx.projectData?` for the project being loaded.
Also use a lit Task to load the project if not already done. In future this can be expanded by using projectInfo (timestamp and parser version) as fingerprint to load from a localstorage cache or something like that.
=> Load project info and project data directly to knx object
