- .yarnrc.yml
- script/merge_requirements.js
- script/upgrade-frontend
to mirror yarn version and properly update frontend repo
updated version of #24
> chore: Update scripts

- .gitignore
- src/knx-router.ts
- src/localize/languages/ca.json
- src/localize/languages/cs.json
- src/localize/languages/de.json
- src/localize/languages/en.json
- src/localize/languages/es.json
- src/localize/languages/et.json
- src/localize/languages/fr.json
- src/localize/languages/it.json
- src/localize/languages/nl.json
- src/localize/languages/ru.json
- src/localize/languages/sk.json
- src/localize/languages/sv.json
- src/localize/localize.ts
- src/main.ts
- src/table/knx-data-table.ts
- src/views/group_monitor.ts
- src/views/overview.ts
Fixes #29
Fixes #37 
Fixes #27 
Fixes #28 
Fixes #31
> feat: Add i18, rename bus monitor, adjust group monitor layout, fix routing

- package.json
- src/main.ts
- yarn.lock
> fix: Content should not overflow header on small screens

- src/views/info.ts
> Confirmation dialog for project data deletion

- script/merge_requirements.js
- script/upgrade-frontend
instead of installing a second pair of `node_modules`.
This reverts #58
> Update HA-FE to specific tag (optional), remove node_modules

- src/table/knx-data-table.ts
- src/views/group_monitor.ts
- src/views/info.ts
- remove unused imports
- extend global typescript definition for knx-data-table
> Cleanup imports and definitions

- src/views/group_monitor.ts
the `rowIndex` can also be used as a handler to get row-data eg. from a `row-clicked` event.
> GroupMonitor: Add telegram number column and sort table by it

- src/knx.ts
- src/main.ts
- src/views/group_monitor.ts
- src/views/info.ts
this has the same signature as `this.hass.localize` and is then usable in components expecting a `localizeFunc` - eg. `"hass-tabs-subpage"`.
> Use `localize` method of KNX object

- src/components/knx-project-tree-view.ts
- src/knx-router.ts
- src/localize/languages/de.json
- src/localize/languages/en.json
- src/utils/format.ts
- src/views/project_explore.ts
- src/views/project_view.ts
GroupRange selector to filter GA table
> Add GroupRange filter for Project view

- src/knx-router.ts
- src/knx.ts
- src/types/knx.ts
as a side effect of trying to understand how this all works together.
> Removed unused stuff in router and knxElement

- build-scripts/gulp/gen-icons-json.js
- build-scripts/gulp/knx.js
- build-scripts/paths.cjs
used by some upstream components at build time
> Genereate `iconList.json`

- src/dialogs/knx-telegram-info-dialog.ts
- src/utils/format.ts
See https://github.com/XKNX/xknx/pull/1277
> Support multi-value DPT data in GroupMonitor

- src/components/knx-project-device-tree.ts
> Add device description in device tree view

- src/dialogs/knx-device-create-dialog.ts
- src/knx-router.ts
- src/knx.ts
- src/views/entities_create.ts
- src/views/entities_view.ts
- src/views/error.ts
- src/views/group_monitor.ts
- src/views/info.ts
navigate to an error page showing the error message.
This happens eg. when the integration is not loaded.
> Handle websocket errors

- src/views/group_monitor.ts
> Add Pause button to GroupMonitor

- src/main.ts
> Support c and e hotkeys

- src/views/project_view.ts
and change column width to flex.
> Remove non-working overflow menu from project view

- src/localize/languages/de.json
- src/localize/languages/en.json
- src/services/websocket.service.ts
- src/views/group_monitor.ts
- src/views/project_view.ts
> Show last value for group address in project tab

- src/components/knx-group-address-selector.ts
fixes https://github.com/home-assistant/core/issues/133949
> Fix scroll reset of group address selector

- src/components/knx-selector-row.ts
- src/types/entity_data.ts
- src/utils/common.ts
- src/utils/schema.ts
| Top - iPhone 12 Size | Scroll a bit |
|--------|--------|
| ![127 0 0 1_8123_knx_entities_create_binary_sensor(iPhone 12 Pro)](https://github.com/user-attachments/assets/789d2f07-ca6b-4d71-ad09-e0f2984e5f8e) | ![127 0 0 1_8123_knx_entities_create_binary_sensor(iPhone 12 Pro) (2)](https://github.com/user-attachments/assets/eb375685-ff9f-4c04-a372-1cf4d62d68cb) |
> Support BinarySensor entities

- src/components/knx-configure-entity-options.ts
- src/components/knx-configure-entity.ts
- src/components/knx-device-picker.ts
- src/types/entity_data.ts
- src/utils/common.ts
- src/utils/schema.ts
- src/views/entities_create.ts
- Replace `ha-settings-row` with `ha-expansion-panel` in `knx-configure-entity` for more unified looks and better readability
- Forward helper attribute in `knx-device-picker`
- Add support for the cover platform
> Add support for the Cover platform

- src/views/entities_view.ts
Related issue: https://github.com/home-assistant/core/issues/133946
> Fix sorting entities data table

- build-scripts/bundle.cjs
- src/views/entities_view.ts
- page not loading when entity is disabled
- state icons not loading
fixes #230
> Fix entities view issues

- .github/copilot-instructions.md
This PR introduces a Copilot instruction file to enhance our project’s integration with GitHub Copilot.
> Add copilot instruction file

- src/features/group-monitor/controller/group-monitor-controller.ts
- src/utils/format.test.ts
- src/utils/format.ts
This PR rewrites the microsecond conversion logic to ensure correct offset calculation in all filter scenarios. Fixes issue #254.
> Fix offset miscalculation in certain filter scenarios
